{% set name = "lpynn" %}
{% set version = "0.0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lpynn-{{ version }}.tar.gz
  sha256: a81a01040fc637073c2b4b3d8cd43b0566cfd4660edec12107db35d44bdfeb9b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - lpython_emulation

test:
  imports:
    - lpynn
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Shaikh-Ubaid/lpython_packages
  summary: A basic neural networks python package
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Shaikh-Ubaid
